Repository Null-By-Design/user-service, pull requests merged in 2024-11, with the labels that each got.

#5 CZN-29: Implement POST /api/v1/user API.
  .github/pull_request_template.md
  README.md
  docker-compose.local.yml
  requirements.txt
  src/api/config/database.py
  src/api/controller/health_controller.py
  src/api/controller/user_controller.py
  src/api/dependencies/provider.py
  src/api/main.py
  src/api/mapper/user_mapper.py
  src/api/model/address.py
  src/api/model/enum.py
  src/api/model/health_check.py
  src/api/model/schemas.py
  src/api/model/user.py
  src/api/repository/user_repository.py
  src/api/service/health_service.py
  src/api/service/user_service.py
  user-service-api/Health.bru
  user-service-api/User.bru
  user-service-api/bruno.json
  user-service-api/environments/user-service LOCAL.bru
Labels: enhancement

#6 CZN-29: Add unit tests.
  .vscode/launch.json
  Makefile
  docker-compose.local.yml
  docs/db.schema.sql
  src/api/config/database.py
  src/api/controller/health_controller.py
  src/api/controller/user_controller.py
  src/api/dependencies/provider.py
  src/api/main.py
  src/api/mapper/user_mapper.py
  src/api/model/address.py
  src/api/model/schemas.py
  src/api/model/user.py
  src/api/repository/user_repository.py
  src/api/service/health_service.py
  tests/test_data.py
  tests/test_health_controller.py
  tests/test_health_service.py
  tests/test_user_controller.py
  tests/test_user_repository.py
  tests/test_user_service.py
  user-service-api/User.bru
Labels: enhancement

#7 CZN-29: Update domain model class.
  src/api/mapper/user_mapper.py
  src/api/model/address.py
  src/api/model/domain.py
  src/api/repository/user_repository.py
  src/api/service/user_service.py
  tests/test_data.py
  tests/test_user_controller.py
  tests/test_user_service.py
Labels: enhancement

#9 Set up GitHub Actions Workflow with Trigger on Push and Pull Request
  .github/workflows/trigger.yml
Labels: enhancement

#12 CZN-48: Configure CI Pipeline - workflows/workflow.yml
  .github/workflows/trigger.yml
  .github/workflows/workflow.yml
Labels: enhancement

#8 GET /user/{id} endpoint
  .vscode/launch.json
  src/api/controller/user_controller.py
  src/api/repository/user_repository.py
  src/api/service/user_service.py
  tests/test_data.py
  tests/test_user_controller.py
  tests/test_user_repository.py
  tests/test_user_service.py
Labels: enhancement

#14 Add QA doc.
  docs/qa/user-service-manual-testing-doc.xlsx
Labels: documentation

#16 CZN-28: Fix GET /v1/user
  docs/qa/user-service-manual-testing-doc.xlsx
  src/api/controller/user_controller.py
  src/api/repository/user_repository.py
  tests/test_user_repository.py
Labels: bug
